TICKETS = [
    {
        "id": "1",
        "user_id": "23",
        "handler_user_id": "24",
        "deskripsi": "Ngga bisa nonton youtube, dsfasdfsd",
        "status": "IN PROGRESS",
        "created_at": "2023-08-09T07:27:57.000Z",
        "updated_at": "2023-08-15T13:00:19.000Z",
        "title": "Jaringan Error",
        "priority": "NORMAL",
        "username": "user1",
        "handler_username": "cs01",
        "email": "aseptjodet@gmail.com"
    },
    {
        "id": "9",
        "user_id": "11",
        "handler_user_id": "26",
        "deskripsi": "gdsagdsagsadgs",
        "status": "CREATED",
        "created_at": "2023-08-15T13:14:08.000Z",
        "updated_at": "2023-08-15T13:14:08.000Z",
        "title": "dafsadgshgrsa",
        "priority": "NORMAL",
        "username": "ADMIN",
        "handler_username": "cs02",
        "email": "aseptjodet@gmail.com"
    },
    {
        "id": "7",
        "user_id": "7",
        "handler_user_id": "24",
        "deskripsi": "Hanya test input ticket, ngga diapa-apain juga ngga apa apa..\n",
        "status": "IN PROGRESS",
        "created_at": "2023-08-14T08:05:50.000Z",
        "updated_at": "2023-08-15T13:34:01.000Z",
        "title": "Just Test",
        "priority": "LOW",
        "username": "anwar",
        "handler_username": "cs01",
        "email": "aseptjodet@gmail.com"
    },
    {
        "id": "2",
        "user_id": "23",
        "handler_user_id": "24",
        "deskripsi": "Ngga bisa akses jaringan",
        "status": "DONE",
        "created_at": "2023-08-09T07:28:14.000Z",
        "updated_at": "2023-08-15T13:34:16.000Z",
        "title": "Jaringan Error",
        "priority": "NORMAL",
        "username": "user1",
        "handler_username": "cs01",
        "email": "aseptjodet@gmail.com"
    },
    {
        "id": "3",
        "user_id": "23",
        "handler_user_id": "24",
        "deskripsi": "Ngga bisa nonton youtube",
        "status": "CREATED",
        "created_at": "2023-08-09T07:28:27.000Z",
        "updated_at": "2023-08-17T15:02:14.000Z",
        "title": "Jaringan Error",
        "priority": "NORMAL",
        "username": "user1",
        "handler_username": "cs01",
        "email": "aseptjodet@gmail.com"
    },
    {
        "id": "11",
        "user_id": "23",
        "handler_user_id": "27",
        "deskripsi": "safdsfsadfsad",
        "status": "OPEN",
        "created_at": "2023-08-17T17:38:03.000Z",
        "updated_at": "2023-08-17T17:38:03.000Z",
        "title": "fdgadsg",
        "priority": "LOW",
        "username": "user1",
        "handler_username": "cs03",
        "email": "aseptjodet@gmail.com"
    },
    {
        "id": "12",
        "user_id": "23",
        "handler_user_id": "27",
        "deskripsi": "gdsagdsafds",
        "status": "OPEN",
        "created_at": "2023-08-17T17:55:54.000Z",
        "updated_at": "2023-08-17T17:55:54.000Z",
        "title": "dasgdsagas",
        "priority": "LOW",
        "username": "user1",
        "handler_username": "cs03",
        "email": "aseptjodet@gmail.com"
    },
    {
        "id": "13",
        "user_id": "23",
        "handler_user_id": "26",
        "deskripsi": "damn its hot",
        "status": "OPEN",
        "created_at": "2023-08-17T18:02:45.000Z",
        "updated_at": "2023-08-17T18:02:45.000Z",
        "title": "DAMN",
        "priority": "LOW",
        "username": "user1",
        "handler_username": "cs02",
        "email": "aseptjodet@gmail.com"
    },
    {
        "id": "14",
        "user_id": "23",
        "handler_user_id": "27",
        "deskripsi": "Ini tidak bisa akses youtube padahal lagi perlu untuk menyelesaikan pekerjaan",
        "status": "OPEN",
        "created_at": "2023-08-17T18:19:06.000Z",
        "updated_at": "2023-08-17T18:19:06.000Z",
        "title": "Tidak bisa akses youtube",
        "priority": "URGENT",
        "username": "user1",
        "handler_username": "cs03",
        "email": "aseptjodet@gmail.com"
    },
    {
        "id": "15",
        "user_id": "23",
        "handler_user_id": "26",
        "deskripsi": "bnbjbhkv,nmnkn jkkjklj;l  lk jk;j k klk l",
        "status": "OPEN",
        "created_at": "2023-08-17T18:46:34.000Z",
        "updated_at": "2023-08-17T18:46:34.000Z",
        "title": "blasblas",
        "priority": "NORMAL",
        "username": "user1",
        "handler_username": "cs02",
        "email": "aseptjodet@gmail.com"
    },
    {
        "id": "6",
        "user_id": "7",
        "handler_user_id": "24",
        "deskripsi": "Email ngga ada yang dateng",
        "status": "DONE",
        "created_at": "2023-08-14T06:55:38.000Z",
        "updated_at": "2023-08-18T03:39:04.000Z",
        "title": "Masalah Email",
        "priority": "NORMAL",
        "username": "anwar",
        "handler_username": "cs01",
        "email": "aseptjodet@gmail.com"
    },
    {
        "id": "5",
        "user_id": "23",
        "handler_user_id": "24",
        "deskripsi": "Monitor matihmnfgjfggfd",
        "status": "IN PROGRESS",
        "created_at": "2023-08-09T10:15:36.000Z",
        "updated_at": "2023-08-18T03:39:53.000Z",
        "title": "Monitor mati",
        "priority": "NORMAL",
        "username": "user1",
        "handler_username": "cs01",
        "email": "aseptjodet@gmail.com"
    },
    {
        "id": "10",
        "user_id": "23",
        "handler_user_id": "26",
        "deskripsi": "Sakit gigi nih, bisa dibantu ngga",
        "status": "CREATED",
        "created_at": "2023-08-17T17:17:25.000Z",
        "updated_at": "2023-08-17T17:17:25.000Z",
        "title": "aduh sakit gigi",
        "priority": "LOW",
        "username": "user1",
        "handler_username": "cs02",
        "email": "aseptjodet@gmail.com"
    },
    {
        "id": "16",
        "user_id": "23",
        "handler_user_id": "27",
        "deskripsi": "Tidak bisa masuk jaringan",
        "status": "OPEN",
        "created_at": "2023-08-18T09:54:49.000Z",
        "updated_at": "2023-08-18T09:54:49.000Z",
        "title": "Tidak bisa masuk jaringan",
        "priority": "URGENT",
        "username": "user1",
        "handler_username": "cs03",
        "email": "aseptjodet@gmail.com"
    },
    {
        "id": "8",
        "user_id": "11",
        "handler_user_id": "26",
        "deskripsi": "fdsfsafsdfsfdsfs",
        "status": "IN PROGRESS",
        "created_at": "2023-08-15T13:13:44.000Z",
        "updated_at": "2023-08-18T09:55:49.000Z",
        "title": "fgdfds",
        "priority": "NORMAL",
        "username": "ADMIN",
        "handler_username": "cs02",
        "email": "aseptjodet@gmail.com"
    }
];
module.exports = TICKETS